[package]

name = "toml_document"
version = "0.0.1"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["encoding", "toml"]

[dev-dependencies]
rustc-serialize = "0.3"